# Generated by Django 3.0.7 on 2020-06-21 01:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=150, null=True)),
                ('height', models.DecimalField(decimal_places=3, default=0.0, max_digits=5)),
                ('width', models.DecimalField(decimal_places=4, default=0.0, max_digits=6)),
                ('weight', models.DecimalField(decimal_places=4, default=0.0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=150, null=True)),
                ('sighted', models.DateTimeField(default=datetime.datetime.now)),
                ('monster', models.ManyToManyField(to='monsters.Monster')),
                ('researcher', models.ManyToManyField(to='monsters.Researcher')),
            ],
        ),
        migrations.CreateModel(
            name='MonsterReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=150, null=True)),
                ('report', models.FileField(null=True, upload_to='media/monsters/reports')),
                ('sighting', models.ManyToManyField(to='monsters.Sighting')),
            ],
        ),
    ]
