# Generated by Django 3.0.7 on 2020-06-21 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0002_monster_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='images',
            field=models.ManyToManyField(to='monsters.Monster_Image'),
        ),
    ]
