# Generated by Django 3.0.2 on 2020-01-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0003_auto_20200124_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='/media/images/150x150.png', upload_to='images/'),
        ),
    ]
