# Generated by Django 3.0.2 on 2020-01-24 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monsters', '0005_auto_20200124_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='monsterreport',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
