# Generated by Django 3.0.2 on 2020-01-26 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0007_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
