# Generated by Django 3.0.2 on 2020-01-26 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monsters', '0008_auto_20200126_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sighting',
            old_name='timestamp',
            new_name='sighted',
        ),
        migrations.RemoveField(
            model_name='monsterreport',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='monsterreport',
            name='path',
        ),
        migrations.RemoveField(
            model_name='monsterreport',
            name='sighting',
        ),
        migrations.RemoveField(
            model_name='monsterreport',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sighting',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='sighting',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='sighting',
            name='monster',
        ),
        migrations.RemoveField(
            model_name='sighting',
            name='researcher',
        ),
        migrations.AddField(
            model_name='monster',
            name='description',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='height',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='monster',
            name='weight',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='monster',
            name='width',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='monsterreport',
            name='description',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='monsterreport',
            name='report',
            field=models.FileField(null=True, upload_to='media/monsters/reports'),
        ),
        migrations.AddField(
            model_name='sighting',
            name='description',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='User_MonsterReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monsterReport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monsters.MonsterReport')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sighting_Researcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('researcher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monsters.Researcher')),
                ('sighting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monsters.Sighting')),
            ],
        ),
        migrations.CreateModel(
            name='Sighting_Monster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monster', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monsters.Monster')),
                ('sighting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monsters.Sighting')),
            ],
        ),
        migrations.CreateModel(
            name='MonsterReport_Sighting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monsterReport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monsters.MonsterReport')),
                ('sighting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monsters.Sighting')),
            ],
        ),
        migrations.CreateModel(
            name='Monster_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/monsters/images')),
                ('monster_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monsters.Monster')),
            ],
        ),
    ]
