# Generated by Django 3.0.2 on 2020-01-26 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monsters', '0009_auto_20200126_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sighting_monster',
            name='monster',
        ),
        migrations.RemoveField(
            model_name='sighting_monster',
            name='sighting',
        ),
        migrations.RemoveField(
            model_name='sighting_researcher',
            name='researcher',
        ),
        migrations.RemoveField(
            model_name='sighting_researcher',
            name='sighting',
        ),
        migrations.RemoveField(
            model_name='user_monsterreport',
            name='monsterReport',
        ),
        migrations.RemoveField(
            model_name='user_monsterreport',
            name='user',
        ),
        migrations.AddField(
            model_name='monsterreport',
            name='sighting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='monsters.Sighting'),
        ),
        migrations.AddField(
            model_name='monsterreport',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sighting',
            name='monster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='monsters.Monster'),
        ),
        migrations.AddField(
            model_name='sighting',
            name='researcher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='monsters.Researcher'),
        ),
        migrations.AlterField(
            model_name='monster_image',
            name='monster_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='monsters.Monster'),
        ),
        migrations.DeleteModel(
            name='MonsterReport_Sighting',
        ),
        migrations.DeleteModel(
            name='Sighting_Monster',
        ),
        migrations.DeleteModel(
            name='Sighting_Researcher',
        ),
        migrations.DeleteModel(
            name='User_MonsterReport',
        ),
    ]
