# Generated by Django 3.0.2 on 2020-01-26 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monsters', '0010_auto_20200126_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monsterreport',
            name='sighting',
        ),
        migrations.RemoveField(
            model_name='monsterreport',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sighting',
            name='monster',
        ),
        migrations.RemoveField(
            model_name='sighting',
            name='researcher',
        ),
        migrations.CreateModel(
            name='User_MonsterReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monsterReport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='monsters.MonsterReport')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sighting_Researcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('researcher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='monsters.Researcher')),
                ('sighting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='monsters.Sighting')),
            ],
        ),
        migrations.CreateModel(
            name='Sighting_Monster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monster', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='monsters.Monster')),
                ('sighting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='monsters.Sighting')),
            ],
        ),
        migrations.CreateModel(
            name='MonsterReport_Sighting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monsterReport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='monsters.MonsterReport')),
                ('sighting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='monsters.Sighting')),
            ],
        ),
    ]
